### ISSUE TITLE
Redesign the extended store connection, supply the file connection and test it with standard S3

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#10]
That is the module can take of the connectivity, remove the submodule mongo and supply file system.

**Comment by electronicpeter** [comment]
package de.adorsys.docusafe.business.subservices;

import org.adorsys.docusafe.service.types.DocumentContent;
import org.adorsys.encobject.complextypes.BucketDirectory;
import org.adorsys.encobject.complextypes.BucketPath;
import org.adorsys.encobject.types.ListRecursiveFlag;

import java.util.List;

public interface DFSConnectionService {

    void putBlob(BucketPath bucketPath, DocumentContent documentContent);

    DocumentContent getBlob(BucketPath bucketPath);

    boolean blobExists(BucketPath bucketPath);

    void removeBlob(BucketPath bucketPath);

    void removeBlobFolder(BucketDirectory bucketDirectory);

    List<BucketPath> list(BucketDirectory bucketDirectory, ListRecursiveFlag listRecursiveFlag);

    List<BucketDirectory> listAllDirectories();
}

**Comment by electronicpeter** [comment]
and the stream interface too

**Comment by electronicpeter** [comment]
- [ ] removal of all metainformation

**Comment by electronicpeter** [comment]
- [ ] remove zip extension in filesystemimplementation

**Comment by valb3r** [comment]
Outdated issue
