### ISSUE TITLE
Design an interface package for the BucketPathEncryptionService

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#11]
that means API Package and implementation like  below

**Comment by electronicpeter** [comment]
package de.adorsys.docusafe.business.subservices;

import org.adorsys.encobject.complextypes.BucketPath;

import javax.crypto.SecretKey;

public interface BucketPathEncryptionService {
    BucketPath encrypt(SecretKey secretKey, BucketPath bucketPath);
    BucketPath decrypt(SecretKey secretKey, BucketPath bucketPath);
}

**Comment by electronicpeter** [comment]
see https://github.com/adorsys/dfs-connection/tree/master/dfs-connection-impl-pathencryption

**Comment by yatsenko-ihor** [comment]
@electronicpeter @valb3r did we decide which crypto algorithm we will use?

**Comment by electronicpeter** [comment]
actually is already done.
Still open a change ihor has not checked in yet?
The interface can be changed back to SecretKey rather than SecretKeySpec.

**Comment by valb3r** [comment]
Outdated issue
