### ISSUE TITLE
Redesign the KeyStoreService

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#13]

**Comment by electronicpeter** [comment]
package de.adorsys.docusafe.business.subservices;

import de.adorsys.docusave.v2.types.PublicKeyIDWithPublicKey;
import org.adorsys.docusafe.business.types.complex.UserIDAuth;
import org.adorsys.encobject.domain.KeyStoreAccess;
import org.adorsys.encobject.domain.KeyStoreAuth;
import org.adorsys.encobject.service.api.generator.KeyStoreCreationConfig;
import org.adorsys.encobject.types.KeyID;
import org.adorsys.encobject.types.SecretKeyIDWithKey;
import org.adorsys.jkeygen.keystore.KeyStoreType;

import javax.crypto.SecretKey;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.util.List;

public interface KeyStoreService {
    KeyStore createKeyStore(KeyStoreAuth keyStoreAuth,
                            KeyStoreType keyStoreType,
                            KeyStoreCreationConfig config);

    List<PublicKeyIDWithPublicKey> getPublicKeys(KeyStoreAccess keyStoreAccess);

    SecretKeyIDWithKey getRandomSecretKeyID(KeyStoreAccess keyStoreAccess);

    SecretKey getSecretKey(KeyStoreAccess keyStoreAccess, KeyID keyID);

    PrivateKey getPrivateKey(UserIDAuth userIDAuth, KeyID keyID);
}

**Comment by valb3r** [comment]
Outdated issue
