### ISSUE TITLE
KeyStoreService: Move the current stand of the current docusafe to Docusafe 2

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#14]

**Comment by electronicpeter** [comment]
from https://github.com/electronicpeter/java.security

**Comment by electronicpeter** [comment]
```
package de.adorsys.docusafe.business.subservices;

import org.adorsys.docusafe.service.types.DocumentContent;
import org.adorsys.encobject.domain.KeyStoreAccess;
import org.adorsys.encobject.types.KeyID;
import org.bouncycastle.cms.CMSEnvelopedData;

import java.security.PublicKey;

public interface CMSEncryptionService {

    CMSEnvelopedData encrypt(DocumentContent data, PublicKey publicKey, KeyID publicKeyID);

    DocumentContent decrypt(CMSEnvelopedData encryptedData, KeyStoreAccess keyStoreAccess);
}
````
separate the CMSEncryptionService

**Comment by electronicpeter** [comment]
```
package de.adorsys.docusafe.business.subservices;

import org.adorsys.docusafe.service.types.DocumentContent;
import org.adorsys.encobject.domain.KeyStoreAccess;
import org.adorsys.encobject.types.KeyID;
import org.bouncycastle.cms.CMSEnvelopedData;

import java.security.PublicKey;

public interface CMSEncryptionService {

    CMSEnvelopedData encrypt(DocumentContent data, PublicKey publicKey, KeyID publicKeyID);

    DocumentContent decrypt(CMSEnvelopedData encryptedData, KeyStoreAccess keyStoreAccess);
}
````
separate the CMSEncryptionService

**Comment by max402** [comment]
Moved to https://github.com/adorsys/docusafe2/tree/feature/DOC2-14_MovingKeystoreService
all that was in java.security repo.
There are dependencies to dfs-connection
Now I'm going to separate CMSEncryption and remove all unnecessary (KeySource)

**Comment by max402** [comment]
Question about CMSEncryption interface. DocumentContent under the hood uses byte array. Shouldn't we use streams instead?

**Comment by electronicpeter** [comment]
yes, you are right. at least we should offer a stream interface too. And as a first implementation it can use the byte interface. But I am not sure, if an envelope can be returned, as long as the input stream is not finished. In this case, the returned envelope may be wrong. This is a topic to investigate.

**Comment by valb3r** [comment]
Outdated issue
