### ISSUE TITLE
path style S3 access is deprecated in AWS environments

### ISSUE THREAD

**Issue by jkroepke** [adorsys/datasafe#175]
* [x] fix path style access in datasafe layer (which is used by simple datasafe adapter)
* [x] provide inbox funcitonality in simple datasafe adapter
* [x] provide inbox functionality in migration layer (by retrieving inbox for 0.6.1 exception will be thrown)
* [ ] creating default bean in migration layer should be triggered by profile
* [x] switch path encryption off for migrated data, but keep it on for not migrated data

Hi,

currently datasafe always access the bucket via path style access which is deprecated in AWS.

See: https://aws.amazon.com/de/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

Example: datasafe use `https://s3.eu-central-1.amazonaws.com/<bucket>/<object-path>` instead `https://<bucket>.s3.amazonaws.com/<object-path>` to access S3 objects.

Please use the virtual-hosted style to access an S3 bucket if the Endpoint is AWS or create a configurable property to enable or disable path style.

**Comment by max402** [comment]
Hi.
We have almost year until September 30, 2020
But of course it would be great to do that and also switch to aws sdk 2
And then check that it doesn't affect performance (run few performance tests and compare them with previous results)

**Comment by jkroepke** [comment]
Hi @valb3r,

I got a mail today with a warning about resolving this issue in datasafe.

While only AWS deprecated path-style access, other S3 implementation depend on it.

I highly recommend a configuration option to enable to disable path style access. I saw this in a lot of other project (for example gitlab or docker registry).

**Comment by valb3r** [comment]
Hi @jkroepke, good to know, thanks for the input it is really appreaciated. We are still waiting on timeslot approval to fix this one

**Comment by francis-pouatcha** [comment]
This is fine for me. I will recommend to proceed forward with the fix. Josiane will coordinate with team to have it fixed.

**Comment by electronicpeter** [comment]
For this issue, fixes have to be done in two Layers.
1) Datasafe: Actually, in datasafe itself it is just the test framework. 
2) SimpleDatasafeAdapter.
3) As Klartax is using the SimpleDatasafeAdapter in the Migration Jar, there some adapterions might have to be done too. At least the default Bean should not be instantiated by Spring, for that a separate Profile would be great. (de.adorsys.datasafe.simple.adapter.spring.DatasafeSpringBeans Bean  SimpleDatasafeService.

4) Further The Klartax needed the inbox functionality of datasafe 1.0.0. It would be a great help for them to add this functionality to the SimpleDatasafeAdapter too. 

5) After all the fixes, the Datasafe has to be released. 
6) After release build Datasafe Migration has to be released too to contain the new Datasafe

The main fix itself is just for the amazonstorage. This is not used in production but in dev Environment only.

**Comment by electronicpeter** [comment]
path fix done in datasafe storage layer and simple datasafe adapter.
To test this explicit besides the regular junit-tests:

1) **datasafe-layer**
de.adorsys.datasafe.business.impl.e2e.BasicFunctionalityTest.listingValidation() one time with amazon and one time with minio by setting AWS_ACCESS_KEY, AWS_SECRET_KEY, AWS_REGION, AWS_BUCKET, AWS_URL. This will force datasafe test layer to use s3 without knowing if it is minio or amazon. In case of amazon AWS_URL can be null or must be https://s3.amazonaws.com.

**Comment by electronicpeter** [comment]
build datasafe-migration.1.0.0.2-SNAPSHOT with datasafe.1.0.0.2-SNAPSHOT.
build datasafe-usage with datasafe-migration.1.0.0.2-SNAPSHOT. Tests on aws work fine for fix.

For old datasafe url for amazon must be https://s3.amazon.com. Otherwise region is not used.

Did test to use path encryption in old (061 version) and no path encryption in new version. WORKS.

**Comment by electronicpeter** [comment]
Release with all features is datasafe 1.0.3.
It is used in datasafe-migration 1.0.3.1.
