### ISSUE TITLE
More restrictive API for String arguments

### ISSUE THREAD

**Issue by valb3r** [adorsys/datasafe#185]
Currently some String based constructors, factory methods that are intended for internal use (i.e. Uri, BasePrivateResource.forPrivate ...) are not safe to use with non-url safe Strings. While it does not affect global usage as *Request api can accept any type of String, it is better to hide those String (Uri, BasePrivateResource.for..) constructors as implementation detail if needed and expose url-safe variants.

**Comment by francis-pouatcha** [comment]
Search and find all API constructors that use String.

**Comment by forkimenjeckayang** [comment]
Greetings  Sir @francis-pouatcha , should this first of all be  a documentation on URL-Safe Strings with regards to an API. Need more clarification on this ticket before working on it.

**Comment by francis-pouatcha** [comment]
It is about locating which rest API have unsafe strings in their parameter.

**Comment by francis-pouatcha** [comment]
Waiting for 
- #245
