### ISSUE TITLE
2.0 Designing the interface of the lookup server

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#2]
(Rest, Service module) to access backend (the Storage of DFS)

**Comment by francis-pouatcha** [comment]
Design the functionality of the lookup server

1. Define the services  offered by a lookup server
2. For each service, 
1. draw a sequence diagram describing how the service is executed in the lookup server
2. define which data are created, stored, manipulated by the lookup server
3. define the embedded service interface
4. define the rest service interface

**Comment by francis-pouatcha** [comment]
dies is [#15](#15 )

**Comment by valb3r** [comment]
Outdated issue
