### ISSUE TITLE
Path clean up after file deletion

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/datasafe#248]
During file deletion datasafe doesn’t check if the path contains other files and thus leaves empty folders.
Steps to reproduce:
store document /deep/path/test.txt
delete document /deep/path/test.txt
result: file is deleted, but empty folder /deep/path remains.

**Comment by NdSaid** [comment]
The problem was solved.

**Comment by francis-pouatcha** [comment]
1. Does datasafe still leaves empty folders?
2. Is there any hin of the resolution of this problem? (commits, tests, pull requests)

Assignee shall ask  @NdSaid

**Comment by Awambeng** [comment]
Datasafe successfully deletes files but keeps empty folders locally and don't display them in the frontend
