### ISSUE TITLE
 Rename DocuSafe to DataSafe 

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#29]
Since our software is not only intended for secure document storage, but also for securing all types of data, we have decided to change the name of our software.

Please rename this in the following:

- [x]  Documentation
- [x] Source Code 
- [x] Repository

**Comment by DoraNziali** [comment]
Since our software is not only intended for secure document storage, but also for securing all types of data, we have decided to change the name of our software. 
Please rename this in the following: 
- [ ] Documentation
- [ ] Source Code and 
- [ ] Repository

**Comment by valb3r** [comment]
@DoraNziali Repository has already proper name -  Docusafe2

**Comment by valb3r** [comment]
Outdated issue.
