### ISSUE TITLE
Fix dependency-plugin warnings

### ISSUE THREAD

**Issue by max402** [adorsys/datasafe#325]
During mvn verify there are maven-dependency-plugin warnings about Used/Unused declared/undeclared dependencies.

To eliminate them, pom.xml dependencies should be reviewed. 
Also ignore rules in maven-dependency-plugin configuration should be adjusted.

**Comment by francis-pouatcha** [comment]
@AssahBismarkabah take over from @Awambeng

**Comment by francis-pouatcha** [comment]
Waiting for @max402 review
