### ISSUE TITLE
expand CMS Encryption with stream en and decryption 

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#5]
That means no more using the proprietary king of encryption with secret keys and documentguard, but using the cms

**Comment by electronicpeter** [comment]
Already done by francis in plooh https://github.com/francis-pouatcha/plh.pkix

**Comment by electronicpeter** [comment]
detailed link https://github.com/francis-pouatcha/plh.pkix/tree/master/plh.pkix.core/plh.pkix.core.smime/src/main/java/org/adorsys/plh/pkix/core/smime/engines

**Comment by valb3r** [comment]
Outdated issue
